spring.application.name=AIProject
server.port=8080
openai.api.url=https://api.openai.com/v1/chat/completions



openai.api.key=${API_KEY}

# WebClient Timeout (Optional)
webclient.timeout=5000


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
